"""Helpers for generating deterministic setup verification scripts."""

from __future__ import annotations

import json

from use_anything.models import AnalyzerIR


def build_verify_setup_script(analysis: AnalyzerIR) -> str:
    required_vars = sorted({item.strip() for item in analysis.setup.env_vars if item.strip()})
    required_vars_json = json.dumps(required_vars)

    return (
        "#!/usr/bin/env python3\n"
        "\"\"\"Generated by use-anything: verify setup prerequisites.\"\"\"\n\n"
        "from __future__ import annotations\n\n"
        "import os\n"
        "import sys\n\n"
        f"REQUIRED_ENV_VARS = {required_vars_json}\n\n"
        "def main() -> int:\n"
        "    if not REQUIRED_ENV_VARS:\n"
        "        print('No required environment variables declared; setup verification passed.')\n"
        "        return 0\n"
        "    missing = [name for name in REQUIRED_ENV_VARS if not os.getenv(name)]\n"
        "    if missing:\n"
        "        print('Missing required environment variables: ' + ', '.join(missing))\n"
        "        return 1\n"
        "    print('Setup verification passed.')\n"
        "    return 0\n\n"
        "if __name__ == '__main__':\n"
        "    raise SystemExit(main())\n"
    )

